### ISSUE TITLE
有关樱镜物语拆包后AS依然无法读取部分文件问题

### ISSUE THREAD

**Issue by wooli2** [28598519a/CherryTale_AssetDecDL#1]
大佬你好，我尝试了用大佬的软件下载樱镜物语的资源后，发现用AS导入还是存在部分没办法读取的情况，文件名是：
assets_resources_honly_baseassets_uiprefabs_simpleprefab_img_hcg_dynamic_b009_03_hcg1_1_spine
assets_resources_honly_baseassets_uiprefabs_simpleprefab_img_hcg_dynamic_b004_01_hcg1_1_spine
大概好几十个文件，如果大佬有空的话请看看什么问题，谢谢大佬！

**Comment by 28598519a** [comment]
確實，看了一下，應該是ChangeVersion byte[]的範圍設不夠大
