### ISSUE TITLE
抱歉又打擾，老問題部分包無法使用

### ISSUE THREAD

**Issue by auntesaunt123** [28598519a/CherryTale_AssetDecDL#10]
如題嘗試替換版本號 還是很多打不開 如下面個範例  (目前發現出問題的都類似這種 只有一小部分我這菜鳥能改改HEX就能用)
assets_resources_honly_baseassets_uiprefabs_simpleprefab_img_hcg_dynamic_story_hcg26_1_spine 
發現有問題圖 和 改了 抱錯圖    辛苦大佬了 無法突破 
![擷取1](https://github.com/28598519a/CherryTale_AssetDecDL/assets/78274359/8fd24852-4c7c-4248-8b0c-16d1f85a26d6)
![擷取2](https://github.com/28598519a/CherryTale_AssetDecDL/assets/78274359/35f016ee-f67f-4f60-a789-4f518f019911)

**Comment by ABCwewe** [comment]
我在包含SPINE的Asset中發現有這些打不開的
`assets_resources_honly_baseassets_uiprefabs_simpleprefab_img_cg_dynamic_e004_01_cg_spine
assets_resources_honly_baseassets_uiprefabs_simpleprefab_img_hcg_dynamic_d008_03_hcg1_1_spine
assets_resources_honly_baseassets_uiprefabs_simpleprefab_img_hcg_dynamic_e002_04_hcg1_1_spine
assets_resources_honly_baseassets_uiprefabs_simpleprefab_img_hcg_dynamic_a002_02_hcg1_1_spine
assets_resources_honly_baseassets_uiprefabs_simpleprefab_img_hcg_dynamic_story_hcg05_1_spine
assets_resources_honly_baseassets_uiprefabs_simpleprefab_img_hcg_dynamic_story_hcg01_1_spine
assets_resources_honly_baseassets_uiprefabs_simpleprefab_img_hcg_dynamic_c007_03_hcg1_1_spine
assets_resources_honly_baseassets_uiprefabs_simpleprefab_img_hcg_dynamic_story_hcg08_1_spine
assets_resources_honly_baseassets_uiprefabs_simpleprefab_img_hcg_dynamic_story_hcg07_1_spine
assets_resources_honly_baseassets_uiprefabs_simpleprefab_img_hcg_dynamic_d002_03_hcg1_1_spine
assets_resources_honly_baseassets_uiprefabs_simpleprefab_img_hcg_dynamic_a005_03_hcg1_1_spine
assets_resources_honly_baseassets_uiprefabs_simpleprefab_img_hcg_dynamic_a002_01_hcg1_1_spine
assets_resources_honly_baseassets_uiprefabs_simpleprefab_img_hcg_dynamic_story_hcg09_1_spine
assets_resources_honly_baseassets_uiprefabs_simpleprefab_img_hcg_dynamic_story_hcg04_1_spine
assets_resources_honly_baseassets_uiprefabs_simpleprefab_img_hcg_dynamic_b005_03_hcg1_1_spine
assets_resources_honly_baseassets_uiprefabs_simpleprefab_img_hcg_dynamic_story_hcg03_1_spine
assets_resources_honly_baseassets_uiprefabs_simpleprefab_img_hcg_dynamic_f002_03_hcg1_1_spine
assets_resources_honly_baseassets_uiprefabs_simpleprefab_img_hcg_dynamic_story_hcg02_1_spine
assets_resources_honly_baseassets_uiprefabs_simpleprefab_img_hcg_dynamic_story_free_hcg01_1_spine
assets_resources_honly_baseassets_uiprefabs_simpleprefab_img_hcg_dynamic_teaching_hcg02_spine
assets_resources_honly_baseassets_uiprefabs_simpleprefab_img_hcg_dynamic_a003_02_hcg1_1_spine
assets_resources_honly_baseassets_uiprefabs_simpleprefab_img_hcg_dynamic_c001_01_hcg1_1_spine
assets_resources_honly_baseassets_uiprefabs_simpleprefab_img_hcg_dynamic_story_hcg23_1_spine
assets_resources_honly_baseassets_uiprefabs_simpleprefab_img_cg_dynamic_fi05_01_cg_spine
assets_resources_honly_baseassets_uiprefabs_simpleprefab_img_hcg_dynamic_b008_02_hcg1_1_spine
assets_resources_honly_baseassets_uiprefabs_simpleprefab_img_hcg_dynamic_story_free_hcg02_1_spine
assets_resources_honly_baseassets_uiprefabs_simpleprefab_img_hcg_dynamic_story_hcg10_1_spine
assets_resources_honly_baseassets_uiprefabs_simpleprefab_img_hcg_dynamic_f002_01_hcg1_1_spine
assets_resources_honly_baseassets_uiprefabs_simpleprefab_img_hcg_dynamic_c003_01_hcg1_1_spine
assets_resources_honly_baseassets_uiprefabs_simpleprefab_img_hcg_dynamic_b008_01_hcg1_1_spine
assets_resources_honly_baseassets_uiprefabs_simpleprefab_img_hcg_dynamic_g025_03_hcg1_1_spine
assets_resources_honly_baseassets_uiprefabs_simpleprefab_img_hcg_dynamic_b007_01_hcg1_1_spine
assets_resources_honly_baseassets_uiprefabs_simpleprefab_img_hcg_dynamic_b003_02_hcg1_1_spine
assets_resources_honly_baseassets_uiprefabs_simpleprefab_img_hcg_dynamic_story_hcg26_1_spine`

**Comment by 28598519a** [comment]
很簡單，因為替換版號的範圍超了，我值設0x800，你把這值再調大一點就行
https://github.com/28598519a/CherryTale_AssetDecDL/blob/a48a42cd4cc5ef7560319c28be9f6e382e927b0a/CherryTale_AssetDecDL/Function/DecryptUnityAsset.cs#L13

因為當初不想跑整個文件查找替換，會很慢，所以直接設一個0~0x800的範圍去替換。不知道有沒有C#大師來個能快速查找並替換byte array的code?

**Comment by 28598519a** [comment]
請嘗試v1.4版本

**Comment by Craftingfan13** [comment]
The files didn't even download. Is there something I need to do on my part, or the the url change, or did something else happen?
![Screenshot 2024-07-08 015029](https://github.com/28598519a/CherryTale_AssetDecDL/assets/156908530/93d2968f-b314-467e-b7f3-45c71c99fb40)
