### ISSUE TITLE
依旧有些文件无法用as打开

### ISSUE THREAD

**Issue by windman9978** [28598519a/CherryTale_AssetDecDL#2]
这些文件的大小集中在4-10kb这个区间。以下是几个例子。
assets_resources_versionshare_plotplayer_event_story_80161
assets_resources_versionshare_plotplayer_event_story_25032
assets_resources_honly_baseassets_sound_charvoicetouch_c002_03_vic_c002_03_tou_par
assets_resources_versionshare_baseassets_uiprefabs_simpleprefab_img_prefabs_img_attack_chase_2

是否是区分v7两个初始值的临界点出现了问题呢？

小弟也想帮忙，可是这游戏的global-metadata.dat是加密的，无法用ill2cpp直接拆解。
是否需要动态调试呢？

**Comment by 28598519a** [comment]
應該是，他這段初始Array應該是有什麼規則，但我當初也沒仔細研究就是，我在處理一下

**Comment by 28598519a** [comment]
喔，我懂了，根本就沒有什麼分界線的問題，自始自終初始Array就是同一個

**Comment by a11s** [comment]
我也是分析对比他同文件前后版本.
发现从文件末尾(EOF) -1018 跳过 -2462 跳过 -3043 这三个定点数. 假设这三个点是abc
以及从文件BOF 跳过1018 (0x3fb),继续跳过2462, 继续跳过3043     假设这三个点是ABC
跳过的意思是 stream.position+= xxx
理想情况是abcCBA
这三对数字交换. a<->A    b<->B  c<->C
另外,有些文件体积小.对比的时候不足三对.比如只有三处位置不同.除了前两对调换之外,中间那个凑不成一对.
例如 aAb
我卡在这里了. 
顺便一提,对称点是可以交叉的.尤其是小文件会有这种交叉问题. 例如 aBbA

原本我以为可以通过统计方法获得一个字典.但是,我自己找到了反例.值不唯一.(需要进一步确认,现在因为个人原因没有继续)
字典大概是 
1	64
2	78
7	94
5f	37
... 这种. 目前没找到规律,可能是随机硬编码


还有啊,我跟踪调试了AssetStudio的源码,发现他的头文件有字节错位(偏移了1个字节),后面的header里面也有偏移(比如m_TargetPlatform之类识别就是int16跟int32的差别).我现在还在加这些东西.
听你们讨论好像直接就能打开了?你们用的哪个版本的assetStudio?

**Comment by a11s** [comment]
@28598519a  没想到你刚好把帖子关了.希望你能看到

**Comment by YasuoQAQ** [comment]
> Reference



> 我也是分析对比他同文件前后版本. 发现从文件末尾(EOF) -1018 跳过 -2462 跳过 -3043 这三个定点数. 假设这三个点是abc 以及从文件BOF 跳过1018 (0x3fb),继续跳过2462, 继续跳过3043 假设这三个点是ABC 跳过的意思是 stream.position+= xxx 理想情况是abcCBA 这三对数字交换. a<->A b<->B c<->C 另外,有些文件体积小.对比的时候不足三对.比如只有三处位置不同.除了前两对调换之外,中间那个凑不成一对. 例如 aAb 我卡在这里了. 顺便一提,对称点是可以交叉的.尤其是小文件会有这种交叉问题. 例如 aBbA
> 
> 原本我以为可以通过统计方法获得一个字典.但是,我自己找到了反例.值不唯一.(需要进一步确认,现在因为个人原因没有继续) 字典大概是 1 64 2 78 7 94 5f 37 ... 这种. 目前没找到规律,可能是随机硬编码
> 
> 还有啊,我跟踪调试了AssetStudio的源码,发现他的头文件有字节错位(偏移了1个字节),后面的header里面也有偏移(比如m_TargetPlatform之类识别就是int16跟int32的差别).我现在还在加这些东西. 听你们讨论好像直接就能打开了?你们用的哪个版本的assetStudio?

0.16.47的版本
