### ISSUE TITLE
3.56KB的文件无法用assetstudio打开

### ISSUE THREAD

**Issue by windman9978** [28598519a/CherryTale_AssetDecDL#3]
感谢大佬发布1.2版本，大部分问题已经解决。
然而仍有一些文件无法读取，它们的大小均为3.56KB(3652bytes)

以下是一些例子
assets_resources_versionshare_plotplayer_event_story_34081
assets_resources_versionshare_plotplayer_event_story_80231
assets_resources_versionshare_plotplayer_event_story_80631

**Comment by 28598519a** [comment]
哦，這個其實是1.1版本就知道的問題，然而屬特例不太想處理，因為目前改版本號是採暴力替換法

你找個Hex編輯器自己替換一下版本號就行，總共12個檔案:
assets_resources_honly_baseassets_sound_charvoicetouch_a007_04_vic_a007_04_tou_bom
assets_resources_honly_baseassets_sound_charvoicetouch_f001_03_vic_f001_03_tou_bom
assets_resources_honly_baseassets_sound_voice_a007_04_vic_a007_04_009
assets_resources_versionshare_baseassets_sound_se_se_ui02_ogg_se_m_male_victory_001
assets_resources_versionshare_baseassets_sound_se_se_ui02_ogg_se_mb_specterdie_002
assets_resources_versionshare_plotplayer_event_story_34081
assets_resources_versionshare_plotplayer_event_story_80231
assets_resources_versionshare_plotplayer_event_story_80631
jajp_global_other_19
kokr_global_other_19
zhcn_global_other_19
zhtw_global_other_19

**Comment by windman9978** [comment]
感谢大佬回答。

我看了一下我提供的例外文件的原始文件，确实版本号比较古怪，如【2020,3.41f1】(点变成了逗号)
这是因为原始加密算法中，第一步先伪装版本号，第二步替换了某些字节。
第二步恰到动到了版本号这里。

所以解密时应先还原被替换的字节，再还原版本号。
也就是
data = DecryptUnityAsset.ChangeVersion(DecryptUnityAsset.ChangeIdx(data));

经小弟实测有效。
然而不太会用github，不知道如何创建分支和提交pullrequest。
就劳烦大佬了。

**Comment by 28598519a** [comment]
> 感谢大佬回答。
> 
> 我看了一下我提供的例外文件的原始文件，确实版本号比较古怪，如【2020,3.41f1】(点变成了逗号) 这是因为原始加密算法中，第一步先伪装版本号，第二步替换了某些字节。 第二步恰到动到了版本号这里。
> 
> 所以解密时应先还原被替换的字节，再还原版本号。 也就是 data = DecryptUnityAsset.ChangeVersion(DecryptUnityAsset.ChangeIdx(data));
> 
> 经小弟实测有效。 然而不太会用github，不知道如何创建分支和提交pullrequest。 就劳烦大佬了。

原來是我解密步驟反了嗎? 哈哈，行，我改一下
