### ISSUE TITLE
非常感谢 请教 404.log 问题

### ISSUE THREAD

**Issue by YasuoQAQ** [28598519a/CherryTale_AssetDecDL#4]
大佬
有17个下载失败了 本来想着自己按着 404.log里的链接下载 但是好像是已经加密的
再运行一遍exe  好像也没下载下来
 [404.log](https://github.com/28598519a/CherryTale_AssetDecDL/files/12535372/404.log)
之前拆包unity碰到的都是未加密的 现在碰到加密的真是一头雾水 有什么地方可以自学解密嘛 求作者指条明路

**Comment by windman9978** [comment]
替作者大佬回答
404.log的内容不是说加密了，而是说服务器没这个资源。
可能是运营那边没放进服务器，或者还没来得及放进去。
可以等一段时间再下载，或者放弃（没有的东西是下载不下来的。）

**Comment by YasuoQAQ** [comment]
> 替作者大佬回答 404.log的内容不是说加密了，而是说服务器没这个资源。 可能是操作系统没停服务器，或者还没来得及及时去。 可以等一段时间再下载，或者放弃（没有的东西是下载不下来的。）

非常感谢 我是个新入坑的小白 可以向你多请教点相关知识嘛

**Comment by 28598519a** [comment]
> 替作者大佬回答 404.log的内容不是说加密了，而是说服务器没这个资源。 可能是运营那边没放进服务器，或者还没来得及放进去。 可以等一段时间再下载，或者放弃（没有的东西是下载不下来的。）

其實是這樣的，他按照404裡的連結手動丟瀏覽器抓的下來表示確實有該資源，考量到此程式下載是使用pool一次丟大量請求去下載檔案，確實有可能因為瞬間斷網(數據機太破)導致部分資料timeout下載失敗

**Comment by 28598519a** [comment]
> 大佬 有17个下载失败了 本来想着自己按着 404.log里的链接下载 但是好像是已经加密的 再运行一遍exe 好像也没下载下来 [404.log](https://github.com/28598519a/CherryTale_AssetDecDL/files/12535372/404.log) 之前拆包unity碰到的都是未加密的 现在碰到加密的真是一头雾水 有什么地方可以自学解密嘛 求作者指条明路

若利用404.log手動確認有該檔案的話，請直接再次運行該程式下載即可 (但請不要刪除已經下載好的檔案，否則可能第一次少A第二次變少B)

**Comment by YasuoQAQ** [comment]
> 

作者大大 我按照你说的做 最后结果有点出入 已经有的资源文件会自动跳过下载（但是会计数到失败数量上）最后结果是 下载失败数量=被跳过文件数量+下载失败数量

**Comment by YasuoQAQ** [comment]
> > 大佬 有17个下载失败了 本来想着自己按着 404.log里的链接下载 但是好像是已经加密的 再运行一遍exe 好像也没下载下来 [404.log](https://github.com/28598519a/CherryTale_AssetDecDL/files/12535372/404.log) 之前拆包unity碰到的都是未加密的 现在碰到加密的真是一头雾水 有什么地方可以自学解密嘛 求作者指条明路
> 
> 若利用404.log手動確認有該檔案的話，請直接再次運行該程式下載即可 (但請不要刪除及移動已經下載好的檔案，否則可能第一次少A第二次變少B)，若第一次17個失敗，第二次直接運行後應該顯示共下載17個檔案
作者大大 我按照你说的做 最后结果有点出入 已经有的资源文件会自动跳过下载（但是会计数到失败数量上）最后结果是 下载失败数量=被跳过文件数量+下载失败数量

**Comment by 28598519a** [comment]
第二次開始你只需要看下載幾個檔案就行，我知道失敗的計數在第二次開始會有這個問題，但我覺得不影響使用

**Comment by YasuoQAQ** [comment]
> 第二次開始你只需要看下載幾個檔案就行，我知道失敗的計數在第二次開始會有這個問題，但我覺得不影響使用
![$%HL7X5R`XEBZUGCBDNS{UP](https://github.com/28598519a/CherryTale_AssetDecDL/assets/64676368/d4352bd2-f909-4e75-8871-4651f05d668c)
不知道是不是因为没开节点的问题  下载的时候我把代理全关了

**Comment by 28598519a** [comment]
那我也沒辦法了，畢竟我自己下載是正常16761個的，代碼我也開源了，你自己手動載下來後，自己呼叫解密函數處理吧

**Comment by YasuoQAQ** [comment]
> 那我也沒辦法了，畢竟我自己下載是正常16761個的，代碼我也開源了，你自己手動載下來後，自己呼叫解密函數處理吧

好的 非常感谢 我试试挂其他地方节点试试

**Comment by YasuoQAQ** [comment]
> @YasuoQAQ 应该也可以手动替换资源文件，自带的资源列表文件可能不是最新的，虽然官方不太可能清理早期版本的cdn资源，但也不排除这种可能性！
> 
> 你也可以自己过滤一下想要的资源，比如**/*.unity3d； 然后用wget去下载，wget的可以设置重试和断点续传； 最重要的是可以比较简单的开多线程下载，然后再用作者大规模的解密。
> 
> BTW：我是e-hentai上的ajc1226，私信你没回，加个好友吧！

看到了
