### ISSUE TITLE
资源网址好像修改了，不能下载了

### ISSUE THREAD

**Issue by cghhj1028** [28598519a/CherryTale_AssetDecDL#5]
大佬能不能提供一个修改地址的接口？这样以后再改能自己修改

或者提供线下解密的功能？

**Comment by boomberman20082009** [comment]
https://pqcc.yunduokeji.com/patch/files/
源码里的App.xaml.cs网址改成上面的就好

**Comment by boomberman20082009** [comment]
https://pqcc.yunduokeji.com/patch/files/
源码都提供了，自己改一下喽
